export const REQUEST_MOVIE = "REQUEST_MOVIE";
export const REQUEST_MOVIE_SUCCESS = "REQUEST_MOVIE_SUCCESS";
export const REQUEST_MOVIE_FAIL = "REQUEST_MOVIE_FAIL";

export const REQUEST_ACTOR = "REQUEST_ACTOR";
export const REQUEST_ACTOR_SUCCESS = "REQUEST_ACTOR_SUCCESS";
export const REQUEST_ACTOR_FAIL = "REQUEST_ACTOR_FAIL";

export const REQUEST_LIST_ACTOR = "REQUEST_LIST_ACTOR";
export const REQUEST_LIST_ACTOR_SUCCESS = "REQUEST_LIST_ACTOR_SUCCESS";
export const REQUEST_LIST_ACTOR_FAIL = "REQUEST_LIST_ACTOR_FAIL";

export const REQUEST_MOVIE_DETAIL = "REQUEST_MOVIE_DETAIL";
export const REQUEST_MOVIE_DETAIL_SUCCESS = "REQUEST_MOVIE_DETAIL_SUCCESS";
export const REQUEST_MOVIE_DETAIL_FAIL = "REQUEST_MOVIE_DETAIL_FAIL";

export const REQUEST_POST = "REQUEST_POST";
export const REQUEST_POST_SUCCESS = "REQUEST_POST_SUCCESS";
export const REQUEST_POST_FAIL = "REQUEST_POST_FAIL";

